Test 7

diff --git a/.github/workflows/run-postman-tests.yaml b/.github/workflows/run-postman-tests.yaml
--- a/.github/workflows/run-postman-tests.yaml
+++ b/.github/workflows/run-postman-tests.yaml
@@ -33,6 +33,10 @@ jobs:
           folders=$(echo "${{ inputs.folders }}" | tr "," "\n")
           
           newman_output_file="newman_output.json"
+          if [[ ! -f "${{ inputs.collection_path }}" ]]; then
+            echo "Error: Environment file does not exist at ${{ inputs.collection_path }}"
+            exit 1
+          fi
           if [[ ! -f "${{ inputs.environment_path }}" ]]; then
             echo "Error: Environment file does not exist at ${{ inputs.environment_path }}"
             exit 1
